### PR TITLE
fix github links on website

### PR DESCRIPTION
**Pull request by cdietrich**
fix github links on website

### CODE REVIEW

**Comment by cdietrich** [comment]
ok with a lot of ache i got ruby 2 running on my spare linux box
@szarnekow my proposal: 
- merge this to main
- merge main to published

test with deadlinkchecker

**Review by szarnekow — APPROVED** [review]
I like the suggested approach.

**Comment by cdietrich** [comment]
@szarnekow looks good

https://github.com/eclipse/xtext/blob/main/CONTRIBUTING.md

is still missing.
what is the new location?

**Comment by LorenzoBettini** [comment]
I was planning to update the contribution guide soon, at least concerning oomph. On another issue/branch? Should I start from an existing guide?

**Comment by szarnekow** [comment]
There is https://github.com/eclipse/xtext/blob/main/Contribute.md

**Comment by cdietrich** [comment]
Ok will change the link to that

**Pull request merged**
