### PR TITLE
Fix Hyperlinking documentation

### PR DESCRIPTION
**Pull request by tfonda-fbk**
Binding a custom ILocationInFileProvider should be done within the DSL's RuntimeModule.

### CODE REVIEW

**Comment by tfonda-fbk** [comment]
Hi @LorenzoBettini 
I see you've been active in this repo lately, any chance you can review this PR? It's a trivial fix, it shouldn't take long :)
Thanks!

**Comment by LorenzoBettini** [comment]
@cdietrich is that correct?
In case, we should regenerate the documentation, right?

**Comment by cdietrich** [comment]
at least some examples do it

**Comment by tfonda-fbk** [comment]
@cdietrich @LorenzoBettini binding a custom ILocationInFileProvider from within the UI module works, but not if the `bindILocationInFileProvider()` method is annotated with `@Override`. The overridable `bindILocationInFileProvider()` resides in the runtime module, hence I wrote this patch.

**Comment by LorenzoBettini** [comment]
OK, then it was really a bug in the documentation :)
I'll merge this, thanks

**Pull request merged**
