### PR TITLE
Replace deprecated XbaseScopeProvider with current THIS constant

### PR DESCRIPTION
**Pull request by stevehickman**

### CODE REVIEW

**Comment by stevehickman** [comment]
The ECA has been updated. How does the test get re-run?

**Comment by cdietrich** [comment]
I hit revalidate but the tool still does not like the commit

**Comment by cdietrich** [comment]
usual steps to commit are

- clone repo
- configure git to use name and email as in eclipse
- commit changes with sign-off (`git -s`)
- create pr

**Comment by stevehickman** [comment]
I did all this editing directly on GitHub where I am logged in. That forked the repo, created the branch, and  signed the commit. I'm currently logged in via the email that is associated with my Eclipse ID.  I followed the link on this PR to my Eclipse ID and signed the ECA after the first commit. I added the second commit just in case that would help.  

I will now try doing this locally.

**Comment by stevehickman** [comment]
See https://github.com/eclipse/xtext-website/pull/18 instead

**Pull request closed without merging**
